name: test
on: [push]
jobs:
  test:
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
    container:
      image: mcr.microsoft.com/playwright:v1.29.0-focal
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # node環境を構築
      - name: Use Node version ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      # packageインストールを行う
      - run: yarn install

      # E2E テストを行うためにインストール
      - name: Install playwright
        run: yarn add playwright chromium

      # NextJSの .next をキャッシュするように
      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      # CI高速化のために node_modules をキャッシュ
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '**/yarn.lock')) }}

      # Visual Regression Testing用に権限付与
      - name: Add permissions
        run: chmod 777 -R .
      # テスト、ビルドを行う
      - name: Build and Test and Visual Regression Testing
        run: yarn build-sqlite && yarn test-start && yarn test-dev

      # E2E テストの結果をartifactに上げる
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test results
          path: |
            playwright/test-results

      # Lighthouse計測
      - name: Lighthouse
        run: yarn add global @lhci/cli@0.10.x
      - name: Build
        run: yarn build
      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
