name: E2E-testing
on: [push]
jobs:
  e2e:
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # node環境を構築
      - name: Use Node version ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      # packageインストールを行う
      - run: yarn install

      # E2E テストを行うためにインストール
      - name: Install playwright
        run: yarn add playwright chromium

      # NextJSの .next をキャッシュするように
      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      # CI高速化のために node_modules をキャッシュ
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      # テスト、ビルドを行う
      - name: Build and test
        run: yarn build:sqlite && yarn test:start && yarn test:dev

      # E2E テストの結果をartifactに上げる
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            playwright/test-results
